id: ig-fhir-doc-cpage
canonical: https://www.cpage.fr/ig/ig-fhir-doc-cpage
name: IG FHIR Doc CPage
status: draft
version: 0.1.0
date: 2025-12-30
title: Guide documentaire IG FHIR CPage
publisher:
  name: CPage
  url: https://www.cpage.fr
contact:
  - name: CPage
    telecom:
      - system: email
        value: contact@cpage.fr
description: >-
  Ce guide propose une documentation complète sur la création, la publication et la maintenance des guides d’implémentation FHIR, à destination de la communauté de l’entreprise.
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: true

dependencies:


pages:
  index.md:
    title: Accueil
  introduction.md:
    title: Introduction
  quickstart.md:
    title: Prise en main rapide
  structure-ig.md:
    title: Structure d’un IG
  structure-pages-menu.md:
    title: Structure des pages & menu
  outils.md:
    title: Outils et technologies
  bonnes-pratiques.md:
    title: Bonnes pratiques
  publication-validation.md:
    title: Publication et validation
  faq.md:
    title: FAQ
  liens-utiles.md:
    title: Liens utiles
  annexes.md:
    title: Annexes
  integration-package.md:
    title: Intégration du package IG FHIR

menu:
  "Accueil": index.html
  "Introduction": introduction.html
  "Prise en main rapide": quickstart.html
  "Structure":
    "Structure d’un IG": structure-ig.html
    "Pages & menu": structure-pages-menu.html
  "Outils et technologies": outils.html
  "Bonnes pratiques": bonnes-pratiques.html
  "Publication & validation": publication-validation.html
  "FAQ": faq.html
  "Liens utiles": liens-utiles.html
  "Annexes": annexes.html
  "Intégration du package IG FHIR": integration-package.html