id: ig-fhir-doc-cpage
canonical: https://www.cpage.fr/ig/ig-fhir-doc-cpage
name: IG FHIR Doc CPage
status: draft
version: 0.1.0
date: 2025-12-30
title: Guide documentaire CPage des guides d'implémentaion FHIR
publisher:
  name: CPage
  url: https://www.cpage.fr
contact:
  - name: CPage
    telecom:
      - system: email
        value: nicolas.moreau@cpage.fr
        use: work
description: >-
  Ce guide propose une documentation complète sur la création, la publication et la maintenance des guides d’implémentation FHIR, à destination de la communauté francophone.
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: true

pages:
  index.md:
    title: Accueil
  quickstart.md:
    title: Prise en main rapide
  structure-pages-menu.md:
    title: Structure des pages & menu
  installation.md:
    title: Installation des outils
  deploiement-publication.md:
    title: Déploiement & publication
  introduction.md:
    title: Introduction
  structure-ig.md:
    title: Structure d’un IG
  structure-projet.md:
    title: Structure du projet
  outils.md:
    title: Outils et technologies
  bonnes-pratiques.md:
    title: Bonnes pratiques
  publication-validation.md:
    title: Publication et validation
  faq.md:
    title: FAQ
  liens-utiles.md:
    title: Liens utiles
  annexes.md:
    title: Annexes

  Accueil: index.html
  "Prise en main rapide": quickstart.html
  "Structure des pages & menu": structure-pages-menu.html
  "Installation des outils": installation.html
  "Déploiement & publication": deploiement-publication.html
  Introduction: introduction.html
  Structure:
    "Structure d'un IG": structure-ig.html
    "Structure du projet": structure-projet.html
  "Outils et technologies": outils.html
  "Bonnes pratiques": bonnes-pratiques.html
  "Publication et validation": publication-validation.html
  FAQ: faq.html
  "Liens utiles": liens-utiles.html
  Annexes: annexes.html

